/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "DIO.h"
#include "MEMORY.h"
#include "CLOCK.h"
#include "TIMERS.h"
#include "INTERRUPT.h"

//#include"stm32f401xe.h"

//#include "stm32f4xx.h"

// #include "stm32f4xx_hal.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


 int main(void)
  {   int x;


   clock_initialization() ;

   dio_intialise();
   //GPIO_pullup_down(GPIOA,PIN0,  PULLUP);
   GPIO_pullup_down(GPIOA,PIN2,  PULLDOWN);
   GPIO_pullup_down(GPIOA,PIN3,  PULLUP);
   GPIO_pullup_down(GPIOA,PIN6,  PULLUP);  /// I intialised for external interrupt
   GPIO_pullup_down(GPIOA,PIN8,  PULLUP);
 // timer2_initi();
timer4_initi();
 //external_interrupt_init();
// time2_interrupt_intialise();

//NVIC_SetPriority(EXTI1_IRQn,1);
//EXTI1_IRQn;
// time2_interrupt_msecond(100);

 pwm_time2_edge_intialise();
 pwm_frequency_deuty_edge(1, 100);
pwm_interrupt_enable();
    while(1)

     {


         for(int x=0; x<=100; x++)
         {
    	pwm_frequency_deuty_edge(x, 100);

    	delaytime4_msec(100);


         }

   //   x=GPIO_read_bit(GPIOA,PIN2);
     // set_GPIO_bit_atomic(GPIOA,PIN5);

 // set_GPIO_bit_atomic(GPIOA,PIN5);
  //delaytime4_msec(1000);

   /* if(x==1)
      {
    	  set_GPIO_bit_atomic(GPIOA,PIN5);
      }else {
    	  //GPIO_toggle_atomic( GPIOA, PIN5  );
    	  clear_GPIO_bit_atomic(GPIOA,PIN5);
      }*/

 //  GPIO_toggle_atomic( GPIOA, PIN5  );
  // delaytime2_msec(5000);



     }
   }













